In [331]:
import numpy as np
import pandas as pd

In [332]:
df=pd.read_csv('imdb_movies_shows.csv')

In [333]:
df

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,['documentation'],['US'],1.0,NaN,NaN,NaN
1,Taxi Driver,MOVIE,1976,R,113,"['crime', 'drama']",['US'],NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"['comedy', 'fantasy']",['GB'],NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,['comedy'],['GB'],NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,['horror'],['US'],NaN,tt0070047,8.1,391942.0
...,...,...,...,...,...,...,...,...,...,...,...
5801,Fine Wine,MOVIE,2021,NaN,100,"['romance', 'drama']",['NG'],NaN,tt13857480,6.9,39.0
5802,Edis Starlight,MOVIE,2021,NaN,74,"['music', 'documentation']",[],NaN,NaN,NaN,NaN
5803,Clash,MOVIE,2021,NaN,88,"['family', 'drama']","['NG', 'CA']",NaN,tt14620732,6.5,32.0
5804,Shadow Parties,MOVIE,2021,NaN,116,"['action', 'thriller']",[],NaN,tt10168094,6.2,9.0
5805,Mighty Little Bheem: Kite Festival,SHOW,2021,NaN,0,"['family', 'comedy', 'animation']",[],1.0,tt13711094,8.8,16.0

In [334]:
#How many rows and columns are there?
df.shape

(5806, 11)

In [335]:
#Display:
#* column names
#* datatype of every column
df.columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5806 entries, 0 to 5805
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   title                 5805 non-null   object
 1   type                  5806 non-null   object
 2   release_year          5806 non-null   int64
 3   age_certification     3196 non-null   object
 4   runtime               5806 non-null   int64
 5   genres                5806 non-null   object
 6   production_countries  5806 non-null   object
 7   seasons               2047 non-null   float64
 8   imdb_id               5362 non-null   object
 9   imdb_score            5283 non-null   float64
 10  imdb_votes            5267 non-null   float64
dtypes: float64(3), int64(2), object(6)
memory usage: 499.1+ KB

In [336]:
#How many missing values are present in every column?
df.isnull().sum()

title                      1
type                       0
release_year               0
age_certification       2610
runtime                    0
genres                     0
production_countries       0
seasons                 3759
imdb_id                  444
imdb_score               523
imdb_votes               539
dtype: int64

In [337]:
#How many Movies and how many TV Shows are there?
type=df.groupby('type').count()
type

,title,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
type,,,,,,,,,,
MOVIE,3758,3759,1406,3759,3759,3759,0,3451,3407,3391
SHOW,2047,2047,1790,2047,2047,2047,2047,1911,1876,1876

In [338]:
 df['type'].value_counts()

type
MOVIE    3759
SHOW     2047
Name: count, dtype: int64

In [339]:
#Find all movies released in 2020.
df[(df['release_year'] == 2020) & (df['type'] == 'MOVIE')]

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
3187,The Rental,MOVIE,2020,R,88,"['thriller', 'drama', 'horror']",['US'],NaN,tt10003008,5.7,29201.0
3191,365 Days,MOVIE,2020,NaN,114,"['romance', 'drama', 'european']",['PL'],NaN,tt10886166,3.3,80198.0
3210,I'm Thinking of Ending Things,MOVIE,2020,R,134,"['thriller', 'fantasy', 'drama']",['US'],NaN,tt7939766,6.6,79921.0
3213,The Devil All the Time,MOVIE,2020,R,138,"['drama', 'thriller', 'crime', 'horror']",['US'],NaN,tt8956406,7.1,122321.0
3215,My Octopus Teacher,MOVIE,2020,NaN,84,['documentation'],"['ZA', 'GB']",NaN,tt12888462,8.1,51232.0
...,...,...,...,...,...,...,...,...,...,...,...
4816,One Take,MOVIE,2020,NaN,85,"['documentation', 'music']",['TH'],NaN,tt12401232,5.9,52.0
4818,#FriendButMarried 2,MOVIE,2020,NaN,104,"['drama', 'comedy', 'romance']",['ID'],NaN,tt11640412,6.9,300.0
4820,Girl's Revenge,MOVIE,2020,NaN,81,['drama'],['TW'],NaN,tt13388018,5.7,190.0
4823,Story of Kale: When Someone's in Love,MOVIE,2020,NaN,77,"['drama', 'romance']",['ID'],NaN,tt13081264,6.4,270.0
4827,Milea,MOVIE,2020,NaN,99,"['romance', 'drama']",['ID'],NaN,tt11127878,6.4,547.0

In [340]:
#How many unique countries are present?
df['production_countries'].nunique()
#->answer not coming right because same country its reading string despite ind and us have came before its treating it new string and 
#also some missing values too

449

In [341]:
df.sample(10)

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
2606,Larva Island,SHOW,2018,TV-Y7,8,"['comedy', 'animation']","['KR', 'US']",2.0,tt9077194,6.6,416.0
3240,The Social Dilemma,MOVIE,2020,PG-13,94,"['drama', 'documentation']",['US'],NaN,tt11464826,7.6,79674.0
3921,Pup Academy,SHOW,2019,TV-Y,26,['family'],['US'],2.0,tt10302548,6.6,498.0
1218,The Last Kingdom,SHOW,2015,TV-MA,55,"['action', 'war', 'drama', 'history', 'european']",['GB'],5.0,tt4179452,8.5,126473.0
3667,Amy Schumer: Growing,MOVIE,2019,NaN,61,['comedy'],['US'],NaN,tt9770590,5.4,3812.0
1188,Mumbai Delhi Mumbai,MOVIE,2014,PG,120,"['comedy', 'romance']",['IN'],NaN,tt4045666,5.7,354.0
1137,Refugiado,MOVIE,2014,R,95,"['drama', 'thriller', 'european']",['AR'],NaN,tt3717390,6.4,365.0
286,Love Actually,MOVIE,2003,R,139,"['drama', 'comedy', 'romance']","['GB', 'US']",NaN,tt0314331,7.6,474176.0
5282,This Is Pop,SHOW,2021,TV-MA,44,"['music', 'documentation']",['CA'],1.0,tt14155414,6.9,1076.0
2291,Carrie Pilby,MOVIE,2017,NaN,98,"['comedy', 'drama']",['US'],NaN,tt6189446,6.7,11311.0

In [342]:
df['production_countries'].dropna()
#here null values are not truly null rather []

0             ['US']
1             ['US']
2             ['GB']
3             ['GB']
4             ['US']
            ...
5801          ['NG']
5802              []
5803    ['NG', 'CA']
5804              []
5805              []
Name: production_countries, Length: 5806, dtype: object

In [343]:
df['production_countries'].value_counts()

production_countries
['US']                      1950
['IN']                       605
['JP']                       266
[]                           232
['GB']                       219
                            ...
['PR', 'US', 'GB', 'CN']       1
['GB', 'US', 'FR']             1
['IT', 'ES', 'FR']             1
['GB', 'US', 'CZ']             1
['NG', 'CA']                   1
Name: count, Length: 449, dtype: int64

In [344]:
df = df[df['production_countries'] != '[]']

In [345]:
df['production_countries'].value_counts()

production_countries
['US']                      1950
['IN']                       605
['JP']                       266
['GB']                       219
['KR']                       210
                            ...
['PR', 'US', 'GB', 'CN']       1
['GB', 'US', 'FR']             1
['IT', 'ES', 'FR']             1
['GB', 'US', 'CZ']             1
['NG', 'CA']                   1
Name: count, Length: 448, dtype: int64

In [346]:
new_df=df['production_countries'].str.split(',', expand=True)
new_df.head()
#->problem is its not comma separated rather in list

        0     1     2     3     4     5     6
0  ['US']  None  None  None  None  None  None
1  ['US']  None  None  None  None  None  None
2  ['GB']  None  None  None  None  None  None
3  ['GB']  None  None  None  None  None  None
4  ['US']  None  None  None  None  None  None

In [347]:
df['production_countries'].head(5)

0    ['US']
1    ['US']
2    ['GB']
3    ['GB']
4    ['US']
Name: production_countries, dtype: object

In [348]:
from ast import literal_eval

df['production_countries'] = df['production_countries'].apply(literal_eval)
#to convert into python list

/var/folders/1b/4rx0vcfj7h19jk43wjg2_b7r0000gn/T/ipykernel_59963/344093610.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['production_countries'] = df['production_countries'].apply(literal_eval)

In [349]:
countries=df['production_countries'].explode()

In [350]:
countries.nunique()

107

In [351]:
#Which country has produced the highest number of Netflix titles?
countries.value_counts()

production_countries
US         2327
IN          629
GB          406
JP          291
FR          248
           ...
DZ            1
Lebanon       1
BF            1
BS            1
FO            1
Name: count, Length: 107, dtype: int64

In [352]:
#Which year had the maximum content added?
df['release_year'].value_counts(ascending=False)

release_year
2019    800
2020    749
2018    748
2021    705
2017    571
       ...
1974      1
1959      1
1962      1
1978      1
1945      1
Name: count, Length: 67, dtype: int64

In [353]:
df

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,['documentation'],[US],1.0,NaN,NaN,NaN
1,Taxi Driver,MOVIE,1976,R,113,"['crime', 'drama']",[US],NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"['comedy', 'fantasy']",[GB],NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,['comedy'],[GB],NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,['horror'],[US],NaN,tt0070047,8.1,391942.0
...,...,...,...,...,...,...,...,...,...,...,...
5798,Time to Dance,MOVIE,2021,NaN,107,"['drama', 'romance']",[IN],NaN,tt8622232,2.2,950.0
5799,HQ Barbers,SHOW,2021,TV-14,24,['comedy'],[NG],1.0,NaN,NaN,NaN
5800,Momshies! Your Soul is Mine,MOVIE,2021,NaN,108,['comedy'],[PH],NaN,tt14412240,5.8,26.0
5801,Fine Wine,MOVIE,2021,NaN,100,"['romance', 'drama']",[NG],NaN,tt13857480,6.9,39.0
5803,Clash,MOVIE,2021,NaN,88,"['family', 'drama']","[NG, CA]",NaN,tt14620732,6.5,32.0

In [354]:
#Find all movies that have an IMDb rating greater than 8.5 and have received more than 50,000 votes.

df[(df['type']=='MOVIE') & (df['imdb_score']>8.5) & (df['imdb_votes']>50000)]

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
108,Forrest Gump,MOVIE,1994,PG-13,142,"['drama', 'romance', 'comedy']",[US],NaN,tt0109830,8.8,1994599.0
111,Saving Private Ryan,MOVIE,1998,R,169,"['drama', 'war']",[US],NaN,tt0120815,8.6,1346020.0
260,Inception,MOVIE,2010,PG-13,148,"['scifi', 'music', 'thriller', 'action']","[GB, US]",NaN,tt1375666,8.8,2268288.0

In [355]:
#Find the top 20 highest-rated movies released after 2015.
df[(df['release_year']>2015) & (df['type']=='MOVIE')].sort_values(by='imdb_score',ascending=False).head(20)

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
3352,David Attenborough: A Life on Our Planet,MOVIE,2020,PG,83,['documentation'],[GB],NaN,tt11989890,9.0,31180.0
2814,C/o Kancharapalem,MOVIE,2018,PG,152,['drama'],[IN],NaN,tt7391996,9.0,6562.0
4944,Bo Burnham: Inside,MOVIE,2021,R,87,"['comedy', 'drama', 'music', 'reality']",[US],NaN,tt14545352,8.7,44074.0
4252,Rubaru Roshni,MOVIE,2019,NaN,110,['documentation'],[IN],NaN,tt9663460,8.7,584.0
5512,In Our Mothers' Gardens,MOVIE,2021,NaN,84,['documentation'],[US],NaN,tt14369930,8.6,124.0
3062,Merku Thodarchi Malai,MOVIE,2018,NaN,122,['drama'],[IN],NaN,tt7794052,8.6,1810.0
3804,"Best Wishes, Warmest Regards: A Schitt's Creek...",MOVIE,2020,NaN,44,['documentation'],[CA],NaN,tt12004838,8.6,1357.0
4143,Emicida: AmarElo - It's All for Yesterday,MOVIE,2020,NaN,89,"['music', 'documentation']",[BR],NaN,tt13458600,8.5,1472.0
2298,Springsteen On Broadway,MOVIE,2018,NaN,153,"['documentation', 'music']",[US],NaN,tt8716334,8.5,2178.0
4621,K. D.,MOVIE,2019,NaN,119,['drama'],[IN],NaN,tt8747560,8.5,1750.0
2946,Ani... Dr. Kashinath Ghanekar,MOVIE,2018,NaN,159,['drama'],[IN],NaN,tt8784906,8.5,1071.0
4770,I'm Glad I Did,MOVIE,2020,NaN,123,['documentation'],[TR],NaN,tt15139398,8.4,1387.0
4214,Our Planet: Behind the Scenes,MOVIE,2019,NaN,63,['documentation'],"[US, GB]",NaN,tt10746342,8.4,1672.0
1398,Bo Burnham: Make Happy,MOVIE,2016,NaN,60,"['comedy', 'music', 'documentation']",[US],NaN,tt5777636,8.4,14356.0
3889,Super Deluxe,MOVIE,2019,NC-17,176,"['thriller', 'action', 'comedy', 'crime', 'dra...",[IN],NaN,tt7019942,8.4,13680.0
1375,Dangal,MOVIE,2016,PG,161,"['action', 'drama', 'sport']",[IN],NaN,tt5074352,8.4,180247.0
4643,Single Slipper Size - 7,MOVIE,2019,NaN,120,"['drama', 'thriller']",[IN],NaN,tt10370116,8.4,3073.0
3538,Dave Chappelle: Sticks & Stones,MOVIE,2019,R,65,['comedy'],[US],NaN,tt10810424,8.4,25687.0
5544,Love is Color Blind,MOVIE,2021,NaN,115,"['romance', 'comedy']",[PH],NaN,tt15979132,8.3,465.0
2361,Taylor Swift: Reputation Stadium Tour,MOVIE,2018,PG-13,125,"['documentation', 'music']",[US],NaN,tt9426852,8.3,5293.0

In [356]:
#Find movies whose runtime is between 90 and 120 minutes.
new_df=df[df['runtime']>90]
new_df[new_df['runtime']<120]
new_df[new_df['type']=='MOVIE']

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
1,Taxi Driver,MOVIE,1976,R,113,"['crime', 'drama']",[US],NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"['comedy', 'fantasy']",[GB],NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,['comedy'],[GB],NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,['horror'],[US],NaN,tt0070047,8.1,391942.0
6,Dirty Harry,MOVIE,1971,R,102,"['thriller', 'crime', 'action']",[US],NaN,tt0066999,7.7,153463.0
...,...,...,...,...,...,...,...,...,...,...,...
5795,The Heartbreak Club,MOVIE,2021,NaN,101,"['comedy', 'drama', 'romance']",[ID],NaN,tt11841144,6.2,188.0
5797,Princess 'Daya'Reese,MOVIE,2021,NaN,115,"['romance', 'comedy']",[PH],NaN,tt13399802,7.2,45.0
5798,Time to Dance,MOVIE,2021,NaN,107,"['drama', 'romance']",[IN],NaN,tt8622232,2.2,950.0
5800,Momshies! Your Soul is Mine,MOVIE,2021,NaN,108,['comedy'],[PH],NaN,tt14412240,5.8,26.0
5801,Fine Wine,MOVIE,2021,NaN,100,"['romance', 'drama']",[NG],NaN,tt13857480,6.9,39.0

In [357]:
#For every type, calculate in one statement:

#* Count
#* Mean IMDb score
#* Mean runtime
#* Maximum IMDb score
#* Minimum IMDb score
#* Total IMDb votes
type_yup=df.groupby('type')
type_yup['imdb_score'].mean(numeric_only=True)

type
MOVIE    6.269091
SHOW     7.034528
Name: imdb_score, dtype: float64

In [358]:
type_yup['type'].count()

type
MOVIE    3607
SHOW     1967
Name: type, dtype: int64

In [359]:
type_yup['runtime'].mean(numeric_only=True)

type
MOVIE    99.899917
SHOW     39.098119
Name: runtime, dtype: float64

In [360]:
type_yup['imdb_score'].max(numeric_only=True)

type
MOVIE    9.0
SHOW     9.5
Name: imdb_score, dtype: float64

In [361]:
type_yup['imdb_score'].min(numeric_only=True)

type
MOVIE    1.5
SHOW     1.6
Name: imdb_score, dtype: float64

In [362]:
type_yup['imdb_votes'].sum()

type
MOVIE    90429687.0
SHOW     32742073.0
Name: imdb_votes, dtype: float64

In [363]:
#Find the top 5 release years having the highest average IMDb score.
ab=df.groupby('release_year')

In [364]:
ab['imdb_score'].mean().sort_values(ascending=False).head(5)

release_year
1985    8.00
1969    7.85
1964    7.80
1967    7.70
1963    7.60
Name: imdb_score, dtype: float64

In [365]:
#For every certification find

#* Average runtime
#* Number of titles
df['age_certification'].value_counts()

age_certification
TV-MA    823
R        572
TV-14    458
PG-13    437
PG       244
TV-PG    176
G        118
TV-Y7    107
TV-Y      94
TV-G      75
NC-17     14
Name: count, dtype: int64

In [366]:
df['age_certification'].isnull().sum()

np.int64(2456)

In [367]:
df = df.dropna(subset=['age_certification'])

In [368]:
df['age_certification'].isnull().sum()

np.int64(0)

In [369]:
cd=df.groupby('age_certification')

In [370]:
cd['runtime'].mean()

age_certification
G         95.322034
NC-17     95.214286
PG       104.762295
PG-13    108.231121
R        105.666084
TV-14     41.925764
TV-G      26.613333
TV-MA     43.614824
TV-PG     35.534091
TV-Y      16.755319
TV-Y7     22.261682
Name: runtime, dtype: float64

In [371]:
cd['type'].value_counts()

age_certification  type
G                  MOVIE    118
NC-17              MOVIE     14
PG                 MOVIE    244
PG-13              MOVIE    437
R                  MOVIE    572
TV-14              SHOW     458
TV-G               SHOW      75
TV-MA              SHOW     823
TV-PG              SHOW     176
TV-Y               SHOW      94
TV-Y7              SHOW     107
Name: count, dtype: int64

In [372]:
df.head()

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,['documentation'],[US],1.0,NaN,NaN,NaN
1,Taxi Driver,MOVIE,1976,R,113,"['crime', 'drama']",[US],NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"['comedy', 'fantasy']",[GB],NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,['comedy'],[GB],NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,['horror'],[US],NaN,tt0070047,8.1,391942.0

In [373]:
#Find the highest-rated movie for every release year.
new_df=df[df['type']=='MOVIE']

In [374]:
idx = new_df.groupby('release_year')['imdb_score'].idxmax()

In [375]:
new_df.loc[idx]

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
7,My Fair Lady,MOVIE,1964,G,170,"['drama', 'music', 'romance', 'family']",[US],NaN,tt0058385,7.8,94121.0
10,The Professionals,MOVIE,1966,PG-13,117,"['western', 'action', 'european']",[US],NaN,tt0060862,7.3,16168.0
9,Bonnie and Clyde,MOVIE,1967,R,110,"['drama', 'crime', 'action']",[US],NaN,tt0061418,7.7,111189.0
6,Dirty Harry,MOVIE,1971,R,102,"['thriller', 'crime', 'action']",[US],NaN,tt0066999,7.7,153463.0
19,FTA,MOVIE,1972,R,97,"['comedy', 'documentation', 'music']",[US],NaN,tt0068562,6.2,411.0
4,The Exorcist,MOVIE,1973,R,133,['horror'],[US],NaN,tt0070047,8.1,391942.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"['comedy', 'fantasy']",[GB],NaN,tt0071853,8.2,530877.0
1,Taxi Driver,MOVIE,1976,R,113,"['crime', 'drama']",[US],NaN,tt0075314,8.3,795222.0
18,Hitler: A Career,MOVIE,1977,PG,150,"['documentation', 'history', 'european']",[DE],NaN,tt0191182,7.5,2416.0
13,Richard Pryor: Live in Concert,MOVIE,1979,R,78,"['comedy', 'documentation']",[US],NaN,tt0079807,8.1,5141.0
14,The Long Riders,MOVIE,1980,R,99,"['western', 'crime']",[US],NaN,tt0081071,6.9,11329.0
63,Endless Love,MOVIE,1981,R,116,"['drama', 'romance']",[US],NaN,tt0082329,4.9,8374.0
72,Monty Python Live at the Hollywood Bowl,MOVIE,1982,R,77,"['comedy', 'documentation']",[GB],NaN,tt0084352,7.9,15186.0
53,Christine,MOVIE,1983,R,90,"['horror', 'thriller', 'european']",[US],NaN,tt0085333,6.7,80945.0
49,Once Upon a Time in America,MOVIE,1984,R,229,"['drama', 'crime', 'european']","[US, IT]",NaN,tt0087843,8.3,342335.0
48,Stand by Me,MOVIE,1986,R,89,['drama'],[US],NaN,tt0092005,8.1,392790.0
52,Full Metal Jacket,MOVIE,1987,R,116,"['drama', 'war']","[GB, US]",NaN,tt0093058,8.3,723306.0
50,When Harry Met Sally...,MOVIE,1989,R,96,"['romance', 'comedy', 'drama']",[US],NaN,tt0098635,7.7,212913.0
56,Awakenings,MOVIE,1990,PG-13,120,"['drama', 'european']",[US],NaN,tt0099077,7.8,137549.0
149,My Girl,MOVIE,1991,PG,103,"['comedy', 'drama', 'family', 'romance', 'euro...",[US],NaN,tt0102492,6.9,79800.0
130,A River Runs Through It,MOVIE,1992,PG,123,['drama'],[US],NaN,tt0105265,7.2,59086.0
225,Sinbad: Afros and Bellbottoms,MOVIE,1993,PG-13,59,"['comedy', 'documentation']",[US],NaN,tt0938331,7.8,166.0
108,Forrest Gump,MOVIE,1994,PG-13,142,"['drama', 'romance', 'comedy']",[US],NaN,tt0109830,8.8,1994599.0
200,Muthu,MOVIE,1995,G,165,"['drama', 'comedy', 'romance', 'action']",[IN],NaN,tt0140399,7.6,3056.0
232,Avvai Shanmugi,MOVIE,1996,PG-13,160,"['drama', 'comedy']",[IN],NaN,tt0139872,7.9,2528.0
115,Gattaca,MOVIE,1997,PG-13,106,"['thriller', 'drama', 'scifi']",[US],NaN,tt0119177,7.8,298168.0
111,Saving Private Ryan,MOVIE,1998,R,169,"['drama', 'war']",[US],NaN,tt0120815,8.6,1346020.0
189,Herod's Law,MOVIE,1999,R,120,"['drama', 'comedy', 'crime']",[MX],NaN,tt0221344,7.8,5943.0
139,The Patriot,MOVIE,2000,R,165,"['drama', 'action', 'history', 'war']","[DE, US]",NaN,tt0187393,7.2,270231.0
397,Lagaan: Once Upon a Time in India,MOVIE,2001,PG,224,"['drama', 'romance', 'sport']",[IN],NaN,tt0169102,8.1,111053.0
277,Road to Perdition,MOVIE,2002,R,117,"['thriller', 'documentation', 'crime', 'drama']",[US],NaN,tt0257044,7.7,263212.0
281,Big Fish,MOVIE,2003,PG-13,125,"['drama', 'fantasy', 'romance']",[US],NaN,tt0319061,8.0,435503.0
524,Black Friday,MOVIE,2004,R,143,"['crime', 'action', 'drama', 'history']",[IN],NaN,tt0400234,8.4,20611.0
310,Corpse Bride,MOVIE,2005,PG,77,"['fantasy', 'romance', 'animation', 'drama', '...",[US],NaN,tt0121164,7.3,265023.0
507,Rang De Basanti,MOVIE,2006,PG-13,157,"['comedy', 'drama', 'history', 'crime']",[IN],NaN,tt0460895,8.1,118092.0
414,Like Stars on Earth,MOVIE,2007,PG,165,"['drama', 'family']",[IN],NaN,tt0986264,8.3,188234.0
341,Ip Man,MOVIE,2008,R,108,"['drama', 'fantasy', 'action', 'history']","[HK, CN]",NaN,tt1220719,8.0,221095.0
368,3 Idiots,MOVIE,2009,PG-13,170,"['comedy', 'drama']",[IN],NaN,tt1187043,8.4,385782.0
260,Inception,MOVIE,2010,PG-13,148,"['scifi', 'music', 'thriller', 'action']","[GB, US]",NaN,tt1375666,8.8,2268288.0
876,Chhota Bheem & Krishna in Mayanagari,MOVIE,2011,G,66,"['animation', 'action', 'fantasy']",[IN],NaN,tt16235600,9.0,5.0
706,Django Unchained,MOVIE,2012,R,165,"['western', 'drama']",[US],NaN,tt1853728,8.4,1472668.0
1211,Chhota Bheem and the ShiNobi Secret,MOVIE,2013,G,63,['animation'],[IN],NaN,tt6417830,8.6,6.0
1033,PK,MOVIE,2014,PG-13,153,"['comedy', 'drama', 'romance', 'fantasy', 'sci...",[IN],NaN,tt2338151,8.2,178012.0
1458,Drishyam,MOVIE,2015,R,163,"['thriller', 'crime', 'drama']",[IN],NaN,tt4430212,8.2,79075.0
1375,Dangal,MOVIE,2016,PG,161,"['action', 'drama', 'sport']",[IN],NaN,tt5074352,8.4,180247.0
1827,Blade Runner 2049,MOVIE,2017,R,164,"['scifi', 'thriller', 'action', 'drama']","[CA, HU, MX, ES, GB, US]",NaN,tt1856101,8.0,539864.0
2814,C/o Kancharapalem,MOVIE,2018,PG,152,['drama'],[IN],NaN,tt7391996,9.0,6562.0
3538,Dave Chappelle: Sticks & Stones,MOVIE,2019,R,65,['comedy'],[US],NaN,tt10810424,8.4,25687.0
3352,David Attenborough: A Life on Our Planet,MOVIE,2020,PG,83,['documentation'],[GB],NaN,tt11989890,9.0,31180.0
4944,Bo Burnham: Inside,MOVIE,2021,R,87,"['comedy', 'drama', 'music', 'reality']",[US],NaN,tt14545352,8.7,44074.0
4924,Downfall: The Case Against Boeing,MOVIE,2022,R,89,['documentation'],[US],NaN,tt11893274,7.4,9428.0

In [376]:
#Find top 15 genres.
df['genres'].isnull().sum()

np.int64(0)

In [377]:
df['genres'].value_counts()

genres
['comedy']                                      167
['drama']                                       131
['documentation']                               106
['reality']                                      88
['comedy', 'drama']                              79
                                               ...
['drama', 'fantasy', 'action']                    1
['drama', 'history', 'war', 'documentation']      1
['thriller', 'fantasy', 'horror', 'drama']        1
['scifi', 'comedy', 'animation', 'fantasy']       1
['music', 'romance', 'comedy']                    1
Name: count, Length: 1222, dtype: int64

In [378]:
new_df=df['genres'].str.split(',', expand=True)
new_df.head()

                   0            1     2     3     4     5     6     7     8
0  ['documentation']         None  None  None  None  None  None  None  None
1           ['crime'     'drama']  None  None  None  None  None  None  None
2          ['comedy'   'fantasy']  None  None  None  None  None  None  None
3         ['comedy']         None  None  None  None  None  None  None  None
4         ['horror']         None  None  None  None  None  None  None  None

In [379]:
from ast import literal_eval

df['genres'] = df['genres'].apply(literal_eval)
#to convert into python list

/var/folders/1b/4rx0vcfj7h19jk43wjg2_b7r0000gn/T/ipykernel_59963/2804744302.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['genres'] = df['genres'].apply(literal_eval)

In [380]:
new_df = df.explode('genres')

In [381]:
new_df.groupby('genres').size().sort_values(ascending=False).head(15)

genres
drama            1667
comedy           1179
thriller          739
action            724
crime             582
romance           505
animation         496
fantasy           484
scifi             482
family            431
documentation     407
horror            242
european          212
reality           166
history           144
dtype: int64

In [382]:
#Find average IMDb score for each genre.
new_df.groupby('genres')['imdb_score'].mean(numeric_only=True)

genres
action           6.668839
animation        6.868201
comedy           6.660243
crime            6.895979
documentation    7.111538
drama            6.924334
european         6.919024
family           6.466038
fantasy          6.756276
history          7.280556
horror           6.322650
music            6.830275
reality          6.545223
romance          6.730219
scifi            6.703922
sport            6.795575
thriller         6.624448
war              7.147475
western          6.915152
Name: imdb_score, dtype: float64

In [383]:
#Find average runtime for each genre.
new_df.groupby('genres')['runtime'].mean(numeric_only=True)

genres
action           71.928177
animation        39.689516
comedy           65.114504
crime            76.429553
documentation    60.837838
drama            75.602280
european         78.882075
family           52.125290
fantasy          59.762397
history          80.875000
horror           73.355372
music            73.360360
reality          41.722892
romance          84.455446
scifi            54.149378
sport            76.716814
thriller         82.331529
war              86.920792
western          94.228571
Name: runtime, dtype: float64

In [384]:
#Which genre has

#highest votes
#highest runtime
#highest rating



a_df=new_df.groupby('genres')['imdb_votes'].mean(numeric_only=True)
a_df.idxmax()

'western'

In [385]:
b_df=new_df.groupby('genres')['runtime'].mean(numeric_only=True)
b_df.idxmax()

'western'

In [386]:
c_df=new_df.groupby('genres')['imdb_score'].mean(numeric_only=True)
c_df.idxmax()

'history'

In [387]:
result = {
    'Metric': [
        'Highest Avg Votes',
        'Highest Avg Runtime',
        'Highest Avg Rating'
    ],
    'Genre': [
        a_df.idxmax(),
        b_df.idxmax(),
        c_df.idxmax()
    ]
}

result_df = pd.DataFrame(result)
result_df

                Metric    Genre
0    Highest Avg Votes  western
1  Highest Avg Runtime  western
2   Highest Avg Rating  history

In [388]:
#Create a table

#| Column | Missing % |

#sorted descending.
df.isnull().sum()

title                      0
type                       0
release_year               0
age_certification          0
runtime                    0
genres                     0
production_countries       0
seasons                 1385
imdb_id                  153
imdb_score               177
imdb_votes               186
dtype: int64

In [389]:
(df.isnull().sum() / len(df)) * 100

title                    0.000000
type                     0.000000
release_year             0.000000
age_certification        0.000000
runtime                  0.000000
genres                   0.000000
production_countries     0.000000
seasons                 44.419500
imdb_id                  4.906992
imdb_score               5.676716
imdb_votes               5.965362
dtype: float64

In [390]:
missing_df = ((df.isnull().sum() / len(df)) * 100).reset_index()
missing_df
#convert to dataframe

                   index          0
0                  title   0.000000
1                   type   0.000000
2           release_year   0.000000
3      age_certification   0.000000
4                runtime   0.000000
5                 genres   0.000000
6   production_countries   0.000000
7                seasons  44.419500
8                imdb_id   4.906992
9             imdb_score   5.676716
10            imdb_votes   5.965362

In [391]:
missing_df.columns = ['Column', 'Missing %']

In [392]:
missing_df.sort_values(by='Missing %', ascending=False)

                  Column  Missing %
7                seasons  44.419500
10            imdb_votes   5.965362
9             imdb_score   5.676716
8                imdb_id   4.906992
0                  title   0.000000
1                   type   0.000000
2           release_year   0.000000
3      age_certification   0.000000
4                runtime   0.000000
5                 genres   0.000000
6   production_countries   0.000000

In [393]:
#Replace missing certification with

#Unknown

#without changing original dataframe.
df['age_certification'].isnull().sum()

np.int64(0)

In [394]:
new = df.copy()

In [395]:
new['age_certification'] = new['age_certification'].fillna('Unknown')

In [396]:
new['age_certification'].isin(['[]']).sum()

np.int64(0)

In [397]:
#Suppose runtime has missing values.Fill them with median runtime within each type.
df['runtime'].isnull().sum()

np.int64(0)

In [398]:
new_df = df.copy()

new_df['runtime'] = new_df['runtime'].fillna(
    new_df.groupby('type')['runtime'].transform('median')
)

In [399]:
new_df

,title,type,release_year,age_certification,runtime,genres,production_countries,seasons,imdb_id,imdb_score,imdb_votes
0,Five Came Back: The Reference Films,SHOW,1945,TV-MA,48,[documentation],[US],1.0,NaN,NaN,NaN
1,Taxi Driver,MOVIE,1976,R,113,"[crime, drama]",[US],NaN,tt0075314,8.3,795222.0
2,Monty Python and the Holy Grail,MOVIE,1975,PG,91,"[comedy, fantasy]",[GB],NaN,tt0071853,8.2,530877.0
3,Life of Brian,MOVIE,1979,R,94,[comedy],[GB],NaN,tt0079470,8.0,392419.0
4,The Exorcist,MOVIE,1973,R,133,[horror],[US],NaN,tt0070047,8.1,391942.0
...,...,...,...,...,...,...,...,...,...,...,...
5783,Dad Stop Embarrassing Me - The Afterparty,MOVIE,2021,PG-13,37,[],[US],NaN,NaN,NaN,NaN
5785,Pitta Kathalu,SHOW,2021,TV-MA,37,"[drama, romance]",[IN],1.0,tt13879000,5.1,727.0
5794,Masameer County,SHOW,2021,TV-MA,23,[],[SA],1.0,NaN,NaN,NaN
5796,The Big Day,SHOW,2021,TV-MA,45,"[reality, romance]",[US],2.0,tt13887518,4.6,327.0
5799,HQ Barbers,SHOW,2021,TV-14,24,[comedy],[NG],1.0,NaN,NaN,NaN

In [403]:
#Find

#mean
#std
#variance
#median
#25 percentile
#75 percentile of imdb score
numpy_df=df['imdb_score'].to_numpy()

In [404]:
np.mean(numpy_df)

np.float64(nan)

In [405]:
df['imdb_score'].info()

<class 'pandas.core.series.Series'>
Index: 3118 entries, 0 to 5799
Series name: imdb_score
Non-Null Count  Dtype
--------------  -----
2941 non-null   float64
dtypes: float64(1)
memory usage: 48.7 KB

In [407]:
df_cleaned = df.dropna()

In [408]:
numpy_df=df_cleaned['imdb_score'].to_numpy()

In [409]:
np.mean(numpy_df)

np.float64(7.049907692307692)

In [410]:
np.std(numpy_df)

np.float64(1.043474222497974)

In [411]:
np.var(numpy_df)

np.float64(1.0888384530177515)

In [412]:
np.median(numpy_df)

np.float64(7.2)

In [413]:
np.percentile(numpy_df,25)

np.float64(6.5)

In [414]:
np.percentile(numpy_df,75)

np.float64(7.8)

In [436]:
#Using Boolean Indexing
#Find percentage of movies having score > mean score
qw=numpy_df[numpy_df>np.mean(numpy_df)]

In [444]:
np.size(qw)/len(numpy_df)*100

55.44615384615385

In [449]:
#Normalize runtime manually using NumPy.
   # (x - x.min()) / (x.max() - x.min())
np.(lambda x: x)
(numpy_df.arr[x]-np.min(numpy_df))/(np.max(numpy_df)-np.min(numpy_df))

SyntaxError: invalid syntax (1248248799.py, line 3)